spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: '123456'
    url: jdbc:mysql://localhost:3306/sy?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
application:
  generator:
    #数据库类型，当前支持mysql
    dbtype: mysql
    #生成文件的类型,当前支持excel和word和html
    target-file-type: excel
    #生成文件的目录
    target-file-dir: D:\generator2\doc