spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 'root'
    url: jdbc:mysql://192.168.0.195:3306/huiyou?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
application:
  generator:
    dbtype: mysql
    target-file-type: word
    target-file-dir: D:\generator