spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 'root'
    url: jdbc:mysql://192.168.0.195:3306/huiyou?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
application:
  generator:
    #数据库类型，当前支持mysql
    dbtype: mysql
    #生成文件的类型,当前支持excel和word和html
    target-file-type: html
    #生成文件的目录
    target-file-dir: D:\generator2\doc